# Generated by Django 5.0.4 on 2024-05-01 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grooming_service', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='user_id',
            new_name='user',
        ),
    ]
