# Generated by Django 5.0.4 on 2024-05-01 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grooming_service', '0002_rename_user_id_pet_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='pet_id',
            new_name='pet',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='service_id',
            new_name='service',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='user_id',
            new_name='user',
        ),
    ]
