# Generated by Django 5.0.4 on 2024-05-06 11:30

import grooming_service.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grooming_service', '0005_user_is_active_user_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'unique': 'This email is already in use.'}, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=50, validators=[grooming_service.validators.Validators.validate_string_input]),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=50, validators=[grooming_service.validators.Validators.validate_string_input]),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(error_messages={'unique': 'This phone number is already in use.'}, max_length=30, unique=True, validators=[grooming_service.validators.Validators.validate_phone_number]),
        ),
    ]
