# Generated by Django 5.0.4 on 2024-05-06 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grooming_service', '0006_alter_user_email_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='price',
        ),
    ]
