# Generated by Django 5.0.4 on 2024-05-06 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grooming_service', '0007_remove_service_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='service_name',
            new_name='name',
        ),
    ]
