# Generated by Django 5.0.4 on 2024-05-06 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grooming_service', '0008_rename_service_name_service_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.IntegerField(choices=[(0, 'available'), (1, 'booked'), (2, 'cancelled')], default=0),
        ),
    ]
