# Generated by Django 5.0.4 on 2024-05-22 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grooming_service', '0015_rename_pet_name_pet_name_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='static/images/nobody.jpg', upload_to='images/'),
        ),
    ]
