# Generated by Django 5.0.4 on 2024-05-22 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grooming_service', '0016_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='/images/go9xwcxemxj7sajmn1zf', upload_to='images/'),
        ),
    ]
