# Generated by Django 5.0.4 on 2024-05-22 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grooming_service', '0017_alter_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='image',
            field=models.ImageField(default='images/tey9seavfcldmybatmmt', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='images/go9xwcxemxj7sajmn1zf', upload_to='images/'),
        ),
    ]
