# Generated by Django 5.0.4 on 2024-05-24 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grooming_service', '0020_service_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='price',
            new_name='vary_price1',
        ),
        migrations.AddField(
            model_name='service',
            name='vary_price2',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
