# Generated by Django 5.0.4 on 2024-05-24 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grooming_service', '0023_remove_appointment_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(default='media/images/rlbpt7uaqhxanu59ro9r', upload_to='images/'),
        ),
    ]
