# Generated by Django 5.0.4 on 2024-05-24 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grooming_service', '0024_service_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='short_description',
            field=models.TextField(default=''),
        ),
    ]
